// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Test.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250601124432___CheckModelDiff")]
    partial class __CheckModelDiff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9929115f-e463-4645-9325-1bebdbda948b")
                        },
                        new
                        {
                            Id = new Guid("53cca54c-213e-4e87-8a1f-7b8cc0922cf4")
                        });
                });

            modelBuilder.Entity("Test.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalMoney")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc65a948-529f-4d62-b53d-0b12ffb01cc8"),
                            CustomerId = new Guid("9929115f-e463-4645-9325-1bebdbda948b"),
                            OrderCode = "ORD001",
                            TotalMoney = 100m
                        },
                        new
                        {
                            Id = new Guid("7c3265ad-91c7-40d6-b429-7817e1e4b3ba"),
                            CustomerId = new Guid("9929115f-e463-4645-9325-1bebdbda948b"),
                            OrderCode = "ORD002",
                            TotalMoney = 200m
                        },
                        new
                        {
                            Id = new Guid("f9016454-09ca-4dbd-9f67-e963dee647e2"),
                            CustomerId = new Guid("9929115f-e463-4645-9325-1bebdbda948b"),
                            OrderCode = "ORD003",
                            TotalMoney = 300m
                        },
                        new
                        {
                            Id = new Guid("2cd4163b-1285-4480-a390-8c72edb83a1a"),
                            CustomerId = new Guid("53cca54c-213e-4e87-8a1f-7b8cc0922cf4"),
                            OrderCode = "ORD004",
                            TotalMoney = 150m
                        },
                        new
                        {
                            Id = new Guid("f49e060b-ef72-4f8f-abdb-dcdba3269f96"),
                            CustomerId = new Guid("53cca54c-213e-4e87-8a1f-7b8cc0922cf4"),
                            OrderCode = "ORD005",
                            TotalMoney = 250m
                        });
                });

            modelBuilder.Entity("Test.Domain.Entities.Views.OrderView", b =>
                {
                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMoney")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("V_Orders", (string)null);
                });

            modelBuilder.Entity("Test.Domain.Entities.Order", b =>
                {
                    b.HasOne("Test.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Test.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
